name: Deploy

# on:
#   push:
#     branches: [ "master" ]

# HERE instead of running below jobs on push, check if integration.yml file has completed then only deployment occur, like if initgration file jobs fail like for ex in test case then this failed/error prune code shoulnt be deployed.

# How this works

# Push/merge → only integration.yml starts.
# If Integration fails (tests broken, lint error, etc.) → deploy.yml is never triggered.
# If Integration passes → GitHub automatically triggers deploy.yml → Docker build + push runs.
on:
  workflow_run:
    workflows: ["Integration"]   # must match the name: Integration above
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # run only if success
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t pj78/code:poll
    - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
    - run: docker push pj78/code:poll
